# Multi-array

In [1]:
import numpy as np


x = np.arange(3)  # / n = 3
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x, y, z])

print(multi_array)
print(multi_array.shape)         # (3,3)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


### np.linspace

In [2]:
import numpy as np

#w = np.linspace(2, 10, 8)
#print('w = ', w)

b = np.arange(1, 30, 3)
print('b = ', b)

c = np.linspace(1, 30, 3)
print('c = ', c)

d = np.linspace(1, 30, 3, False)
print('d = ', d)

b =  [ 1  4  7 10 13 16 19 22 25 28]
c =  [ 1.  15.5 30. ]
d =  [ 1.         10.66666667 20.33333333]


### multi-array indexing

In [3]:
import numpy as np

x = np.arange(1, 4)  # / n = 3
y = np.arange(4, 7)
z = np.arange(7, 10)

multi_array = np.array([x, y, z])

print(multi_array)
print(multi_array.shape)

print(multi_array[0, 2])  # row 0 and col 2
print(multi_array[1, 1])

print(multi_array.dtype)  # int 64

multi_array = np.array([x, y, z], dtype = np.int32)
print(multi_array.dtype)  # int 32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
3
5
int32
int32


___