## Multidim Slicing

In [1]:
import numpy as np

x = np.arange(18).reshape(3, 2, 3)
print(x)
print(x[2, 1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[15 16 17]


In [2]:
x = np.arange(18).reshape(3, 2, 3)

print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [3]:
# / indexing
print(x[1, 1, 1])

10


In [4]:
# / slicing
print(x[1, 0:2, 0:3])

print(x[1, 0:, 0:])

print(x[1, :, :])

print(x[ : , 0, 0] )

print(x[ : , : , :  :2])

[[ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 9 10 11]]
[ 0  6 12]
[[[ 0  2]
  [ 3  5]]

 [[ 6  8]
  [ 9 11]]

 [[12 14]
  [15 17]]]


### Conditional Selection

In [5]:
import numpy as np

x = np.arange(18).reshape(3, 2, 3)

comparison_operation = x > 5

print(comparison_operation)

print(x[comparison_operation])

print(x[x > 5])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
