# Manipulating Array Shapes

In [2]:
import numpy as np

### ravel() and flatten()

In [3]:
import numpy as np

x = np.arange(9).reshape(3, 3)
print(x)

raveled_array = x.ravel()
print(raveled_array)

flattened_array = x.flatten()
print(flattened_array)

raveled_array[2] = 547841
print('raveled_array = ', raveled_array)
print('x = ', x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
raveled_array =  [     0      1 547841      3      4      5      6      7      8]
x =  [[     0      1 547841]
 [     3      4      5]
 [     6      7      8]]


### Shape and Transpose

In [4]:
y = np.arange(9)
y.shape = (3, 3)
print(y)

print(y.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


### Resizing

In [5]:
y = np.arange(9)
y.shape = (3, 3)
print('y = ', y)

y = np.resize(y, (6, 6) )

print('new y = ', y)

y =  [[0 1 2]
 [3 4 5]
 [6 7 8]]
new y =  [[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


### Zeros, Ones and Eye

In [6]:
print(np.zeros(6, dtype=int))

print(np.zeros((2, 3), dtype=int))

print(np.eye(3) )

[0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Creating Arrays with Random Numbers

In [7]:
x = np.random.rand(4, 4)
print(x)

[[0.39196996 0.73405923 0.25415578 0.98721103]
 [0.86890606 0.91739825 0.64956386 0.4937492 ]
 [0.35658275 0.08774806 0.83359397 0.57559618]
 [0.14223617 0.86092098 0.26858414 0.14760317]]
