## Matrix Multiplication

In [1]:
import numpy as np

In [2]:
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2,3)
print('mat A = \n', mat_a)
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
print('mat B = \n', mat_b)

mat A = 
 [[0 3 5]
 [5 5 2]]
mat B = 
 [[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [3]:
mat_ab = mat_a * mat_b
print('mat AB = \n', mat_ab)

mat AB = 
 [[ 29 -16]
 [ 38   6]]


In [4]:
mat_AB = np.matmul(mat_a, mat_b)
print('mat_AB = \n', mat_AB)

mat_AB = 
 [[ 29 -16]
 [ 38   6]]


In [5]:
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]
