# Stacking

In [1]:
import numpy as np

### H-Stack

In [2]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)

y = np.arange(4, 8).reshape(2,2)
print('y = \n', y)

x = 
 [[0 1]
 [2 3]]
y = 
 [[4 5]
 [6 7]]


In [3]:
z = np.hstack( (x,y) )
print('z = \n', z)

z = 
 [[0 1 4 5]
 [2 3 6 7]]


### V-Stack

In [4]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)

y = np.arange(4, 8).reshape(2,2)
print('y = \n', y)

x = 
 [[0 1]
 [2 3]]
y = 
 [[4 5]
 [6 7]]


In [5]:
z = np.vstack( (x,y) )
print('z = \n', z)

z = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Concatenate

In [6]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)

y = np.arange(4,8).reshape(2,2)
print('y = \n', y)

x = 
 [[0 1]
 [2 3]]
y = 
 [[4 5]
 [6 7]]


In [7]:
z = np.concatenate( (x,y), axis=1)  # horizontal stacking
print('z = \n', z)

w = np.hstack( (x,y) )
print('w = \n', w)

print(z == w)

z = 
 [[0 1 4 5]
 [2 3 6 7]]
w = 
 [[0 1 4 5]
 [2 3 6 7]]
[[ True  True  True  True]
 [ True  True  True  True]]


In [8]:
z = np.concatenate( (x,y), axis=0) # vertical stacking
print('z = \n', z)

z = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Depth Stacking

In [9]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)
print(x.shape)

y = np.arange(4,8).reshape(2,2)
print('y = \n', y)
print(y.shape)

x = 
 [[0 1]
 [2 3]]
(2, 2)
y = 
 [[4 5]
 [6 7]]
(2, 2)


In [10]:
depth_stack = np.dstack( (x, y) )
print('depth stack = \n', depth_stack)

print(depth_stack.shape)

depth stack = 
 [[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]
(2, 2, 2)


### Col-Stack

In [11]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)
print(x.shape)

y = np.arange(4,8).reshape(2,2)
print('y = \n', y)
print(y.shape)

x = 
 [[0 1]
 [2 3]]
(2, 2)
y = 
 [[4 5]
 [6 7]]
(2, 2)


In [12]:
col_stack = np.column_stack( (x, y) )
print('col stack = \n', col_stack)
print(col_stack.shape)

col stack = 
 [[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [13]:
h_stack = np.hstack( (x,y) )
print(h_stack)

[[0 1 4 5]
 [2 3 6 7]]


### Row_Stack

In [14]:
x = np.arange(4).reshape(2,2)
print('x = \n', x)
print(x.shape)

y = np.arange(4,8).reshape(2,2)
print('y = \n', y)
print(y.shape)

x = 
 [[0 1]
 [2 3]]
(2, 2)
y = 
 [[4 5]
 [6 7]]
(2, 2)


In [15]:
row_stack = np.row_stack( (x,y) )   ## depricated (not used anymore)
print('row stack = \n', row_stack)
print(row_stack.shape)

row stack = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [16]:
v_stack = np.vstack( (x,y) )
print(v_stack)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
